version: "3.8"

services:
  app:
    image: dberrocal/platzi-quarkus:0.0.2
    environment:
      quarkus.mongodb.connection-string: "mongodb://mongo_db:27017/platzi"
    ports:
      - "80:8080" 
    depends_on:
      - db
    networks:
      - platzi-net

  db:
    container_name: mongo_db
    image: mongo:4.4.6
    ports:
      - "27017:27017"
    #environment:
    #  MONGO_INITDB_ROOT_USERNAME: "root"
    #  MONGO_INITDB_ROOT_PASSWORD: "admin"
    volumes:
      - mongo_db_data:/data/db
    networks:
      - platzi-net

networks:
  platzi-net:
    external: true
    name: platzi-net
  
volumes:
  mongo_db_data:
    external: true
    name: mongo_db_data
  
